# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
# Store filepath in a variable
file_one = "../output_data/cities.csv"
weather_df = pd.read_csv(file_one)
weather_df.head()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Vardø,40,NO,1588185189,86,70.37,31.11,28.40,11.41
1,Albany,99,US,1588184959,53,42.60,-73.97,60.01,3.00
2,Ushuaia,99,AR,1588184915,70,-54.80,-68.30,46.40,19.46
3,Kolvereid,10,NO,1588185190,45,64.87,11.60,48.20,9.17
4,Faya,87,SA,1588185190,68,18.39,42.45,69.80,4.70

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps
gmaps.configure(api_key=g_key)

# Store latitude and longitude in locations
locations = weather_df[["Lat", "Lng"]]

# Store humidity values
humidity = weather_df["Humidity"]

In [5]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=3)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

A max temperature lower than 80 degrees but higher than 70.


Wind speed less than 10 mph.


Zero cloudiness.

In [6]:
ideal_weather_df = weather_df.loc[(weather_df["Max Temp"] >= 70) & 
                                  (weather_df["Max Temp"] <= 80) & 
                                  (weather_df["Wind Speed"] <= 10) & 
                                  (weather_df["Cloudiness"] == 0)
                                  , :]

ideal_weather_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
31,Reconquista,0,AR,1588185194,30,-29.15,-59.65,77.20,6.33
77,Angoche,0,MZ,1588185262,73,-16.23,39.91,76.77,4.18
137,Caravelas,0,BR,1588185332,72,-17.71,-39.25,77.97,6.31
146,Bulungu,0,CD,1588185394,76,-4.55,18.60,73.99,1.16
170,Yangcun,0,CN,1588185398,53,39.36,117.06,71.60,2.24
227,Korla,0,CN,1588185468,13,41.76,86.15,75.56,9.46
367,Koumac,0,NC,1588185670,83,-20.57,164.28,72.79,5.23
402,Lima,0,PE,1588185654,73,-12.04,-77.03,71.60,9.17
407,Creel,0,MX,1588185736,7,27.75,-107.63,77.67,6.40
418,Itapetininga,0,BR,1588185798,41,-23.59,-48.05,75.83,5.37
445,Pingyin,0,CN,1588185803,49,36.28,116.45,77.00,1.01
451,Keetmanshoop,0,NaN,1588185804,33,-26.58,18.13,71.60,4.70
462,Bhūm,0,IN,1588185866,45,18.47,75.67,78.28,6.93
469,Santa Maria,0,BR,1588185868,57,-29.68,-53.81,77.00,4.70
553,Basoko,0,CD,1588186002,72,1.24,23.62,75.43,3.09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
hotel_df = ideal_weather_df
hotel_df['Hotel Name'] = ""
hotel_df

/Users/beastmode/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
31,Reconquista,0,AR,1588185194,30,-29.15,-59.65,77.20,6.33,
77,Angoche,0,MZ,1588185262,73,-16.23,39.91,76.77,4.18,
137,Caravelas,0,BR,1588185332,72,-17.71,-39.25,77.97,6.31,
146,Bulungu,0,CD,1588185394,76,-4.55,18.60,73.99,1.16,
170,Yangcun,0,CN,1588185398,53,39.36,117.06,71.60,2.24,
227,Korla,0,CN,1588185468,13,41.76,86.15,75.56,9.46,
367,Koumac,0,NC,1588185670,83,-20.57,164.28,72.79,5.23,
402,Lima,0,PE,1588185654,73,-12.04,-77.03,71.60,9.17,
407,Creel,0,MX,1588185736,7,27.75,-107.63,77.67,6.40,
418,Itapetininga,0,BR,1588185798,41,-23.59,-48.05,75.83,5.37,
445,Pingyin,0,CN,1588185803,49,36.28,116.45,77.00,1.01,
451,Keetmanshoop,0,NaN,1588185804,33,-26.58,18.13,71.60,4.70,
462,Bhūm,0,IN,1588185866,45,18.47,75.67,78.28,6.93,
469,Santa Maria,0,BR,1588185868,57,-29.68,-53.81,77.00,4.70,
553,Basoko,0,CD,1588186002,72,1.24,23.62,75.43,3.09,

In [8]:
# Find the closest hotel of each city coordinates

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "location": "latitude,longitude",  
    "rankby": "distance",
    "type": "hotel",
    "key": g_key,
}
# use iterrows to iterate through pandas dataframe
for index, row in hotel_df.iterrows():

    # get lat/lng data from hotel_df
    lat = row['Lat']
    lng = row['Lng']

    # add location to params dict
    params['location'] = f'{lat},{lng}'

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}.")
    response = requests.get(base_url, params=params).json()

    # extract results
    results = response['results']

    try:
        print(f"Closest hotel is {results[0]['name']}.")
        
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']

    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 31.
Closest hotel is SSSSSS.
------------
Retrieving Results for Index 77.

/Users/beastmode/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Closest hotel is Boy's guest house.
------------
Retrieving Results for Index 137.
Closest hotel is Mateus' S/A.
------------
Retrieving Results for Index 146.
Missing field/result... skipping.
------------
Retrieving Results for Index 170.
Closest hotel is 第六城-新香港城.
------------
Retrieving Results for Index 227.
Closest hotel is Bazhou People's Hospital Workers Muslim Restaurant.
------------
Retrieving Results for Index 367.
Closest hotel is STATION MOBIL LA FOA.
------------
Retrieving Results for Index 402.
Closest hotel is Trujillo - NS - SIT303.
------------
Retrieving Results for Index 407.
Closest hotel is Unidad de rehabilitación Creel.
------------
Retrieving Results for Index 418.
Closest hotel is Foto Aurora.
------------
Retrieving Results for Index 445.
Closest hotel is Limei Firm.
------------
Retrieving Results for Index 451.
Closest hotel is Municipal Camp & Caravan Park.
------------
Retrieving Results for Index 462.
Closest hotel is धनंजय होम.
------------
Retrieving Results for Index 469.
Closest hotel is Marcia Glass Design Interiores.
------------
Retrieving Results for Index 553.
Closest hotel is Flat Hotel La Benediction.
------------

In [9]:
hotel_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
31,Reconquista,0,AR,1588185194,30,-29.15,-59.65,77.20,6.33,SSSSSS
77,Angoche,0,MZ,1588185262,73,-16.23,39.91,76.77,4.18,Boy's guest house
137,Caravelas,0,BR,1588185332,72,-17.71,-39.25,77.97,6.31,Mateus' S/A
146,Bulungu,0,CD,1588185394,76,-4.55,18.60,73.99,1.16,
170,Yangcun,0,CN,1588185398,53,39.36,117.06,71.60,2.24,第六城-新香港城
227,Korla,0,CN,1588185468,13,41.76,86.15,75.56,9.46,Bazhou People's Hospital Workers Muslim Restau...
367,Koumac,0,NC,1588185670,83,-20.57,164.28,72.79,5.23,STATION MOBIL LA FOA
402,Lima,0,PE,1588185654,73,-12.04,-77.03,71.60,9.17,Trujillo - NS - SIT303
407,Creel,0,MX,1588185736,7,27.75,-107.63,77.67,6.40,Unidad de rehabilitación Creel
418,Itapetininga,0,BR,1588185798,41,-23.59,-48.05,75.83,5.37,Foto Aurora
445,Pingyin,0,CN,1588185803,49,36.28,116.45,77.00,1.01,Limei Firm
451,Keetmanshoop,0,NaN,1588185804,33,-26.58,18.13,71.60,4.70,Municipal Camp & Caravan Park
462,Bhūm,0,IN,1588185866,45,18.47,75.67,78.28,6.93,धनंजय होम
469,Santa Maria,0,BR,1588185868,57,-29.68,-53.81,77.00,4.70,Marcia Glass Design Interiores
553,Basoko,0,CD,1588186002,72,1.24,23.62,75.43,3.09,Flat Hotel La Benediction

In [10]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [11]:
# Add marker layer ontop of heat map
# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
# Add the layer to the map
fig.add_layer(markers)
fig

# Display Map

Figure(layout=FigureLayout(height='420px'))